package(default_visibility = ["//visibility:public"])

filegroup(
    name = "fastfilter_ffi_wrapper.c",
    srcs = ["fastfilter_ffi_wrapper.c"],
)

filegroup(
    name = "all_c_files",
    srcs = glob(["*.c", "*.h"]),
)